const sites:Record<string,string>={sierra:"https://sierra.ai/",decagon:"https://decagon.ai/",harvey:"https://www.harvey.ai/",cognition:"https://cognition.ai/",glean:"https://www.glean.com/",gradial:"https://gradial.com/"};
function clean(value:string){return value.replace(/<script[\s\S]*?<\/script>/gi," ").replace(/<style[\s\S]*?<\/style>/gi," ").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/&#39;/g,"'").replace(/&quot;/g,'"').replace(/\s+/g," ").trim()}
function meta(html:string,name:string){const a=html.match(new RegExp(`<meta[^>]+(?:name|property)=["']${name}["'][^>]+content=["']([^"']+)["']`,"i"));const b=html.match(new RegExp(`<meta[^>]+content=["']([^"']+)["'][^>]+(?:name|property)=["']${name}["']`,"i"));return clean(a?.[1]||b?.[1]||"")}
async function digest(text:string){const data=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(text));return Array.from(new Uint8Array(data)).slice(0,8).map(x=>x.toString(16).padStart(2,"0")).join("")}
async function scan(id:string){const url=sites[id];try{const response=await fetch(url,{headers:{"user-agent":"Agent50ResearchMonitor/1.0"},signal:AbortSignal.timeout(8000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const html=(await response.text()).slice(0,600000);const title=clean(html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]||"");const description=meta(html,"description")||meta(html,"og:description");const text=clean(html).slice(0,7000);return{id,ok:true,url,title,description,text,fingerprint:await digest(`${title}|${description}|${text}`),httpLastModified:response.headers.get("last-modified"),scannedAt:new Date().toISOString()}}catch(error){return{id,ok:false,url,error:error instanceof Error?error.message:"Scan failed",scannedAt:new Date().toISOString()}}
}
export async function POST(request:Request){const body=await request.json();const requested=(body.companies||[]).filter((c:{id:string})=>sites[c.id]);const raw=await Promise.all(requested.map((c:{id:string})=>scan(c.id)));const key=process.env.TYPESAFE_API_KEY;if(!key)return Response.json({jev:false,scannedAt:new Date().toISOString(),results:raw.map(({text,...r}:any)=>({...r,changeType:r.ok?"source refreshed":"unavailable"}))});const state={companies:raw.map((r:any)=>{const baseline=requested.find((c:{id:string})=>c.id===r.id)?.baseline;return{id:r.id,baseline,current_title:r.title,current_description:r.description,current_page_text:r.text?.slice(0,3500),fetch_ok:r.ok}})};const scoreCriteria=["No strategically meaningful positioning change is visible","A minor wording or emphasis change is visible","A meaningful product, audience, or go-to-market shift is visible","A major repositioning, new category, or major launch is visible"];
 const questions:any={};for(const c of requested){questions[`${c.id}_change_type`]={type:"choice",instructions:`Classify the strongest positioning signal on the current website for \`companies.${c.id}\` relative to its baseline.`,criteria:{stable:"Same core positioning",product_expansion:"New product or capability emphasis",audience_expansion:"New customer or market emphasis",proof_update:"New traction, customer, or outcome proof",pricing_shift:"Pricing or commercial-model change",major_repositioning:"Fundamental category or positioning change",insufficient_evidence:"Website evidence is missing or insufficient"}};questions[`${c.id}_impact`]={type:"score",instructions:`How strategically important is the visible website positioning change for \`companies.${c.id}\`?`,criteria:scoreCriteria};questions[`${c.id}_material`]={type:"noul",instructions:`Does the current website evidence for \`companies.${c.id}\` indicate a material competitive move worth human review?`}}
 const response=await fetch("https://api.typesafe.ai/v1/systemone",{method:"POST",headers:{authorization:`Bearer ${key}`,"content-type":"application/json"},body:JSON.stringify({state,model:"jev-latest",questions})});if(!response.ok)return Response.json({jev:false,scannedAt:new Date().toISOString(),results:raw.map(({text,...r}:any)=>({...r,changeType:r.ok?"source refreshed":"unavailable"}))});const data:any=await response.json();return Response.json({jev:true,scannedAt:new Date().toISOString(),results:raw.map(({text,...r}:any)=>({...r,changeType:data.answers?.[`${r.id}_change_type`]?.choice,impact:data.answers?.[`${r.id}_impact`]?.score,material:data.answers?.[`${r.id}_material`]?.noul}))})}
